<?php
// This file is auto-generated by local_multitenancy. Do not edit manually.

return array (
  'test01' => 
  array (
    'shortcode' => 'test01',
    'name' => 'test01',
    'enabled' => 1,
    'wwwroot' => 'test01',
    'dataroot' => 'test01',
    'dbhost' => 'localhost',
    'dbname' => 'test01',
    'dbuser' => 'root',
    'dbpass' => 'root',
    'prefix' => 'mdl_',
    'dbtype' => 'mysqli',
    'dblibrary' => 'native',
    'dboptions' => 
    array (
    ),
  ),
);
