<?php
// This file is auto-generated by local_multitenancy. Do not edit manually.

return array (
  'routing' => 'rewrite',
  'path_prefix' => '/multitenancy',
  'by_shortcode' => 
  array (
    '01' => 
    array (
      'shortcode' => '01',
      'name' => 'ca01',
      'enabled' => 1,
      'wwwroot' => 'https://dev.moodle/multitenancy/01',
      'dataroot' => 'ca01',
      'dbhost' => 'localhost',
      'dbname' => 'moodleca01',
      'dbuser' => 'root',
      'dbpass' => 'root',
      'prefix' => 'mdl_',
      'dbtype' => 'mysqli',
      'dblibrary' => 'native',
      'dboptions' => 
      array (
      ),
    ),
    'mattan' => 
    array (
      'shortcode' => 'mattan',
      'name' => 'mattan',
      'enabled' => 1,
      'wwwroot' => 'https://dev.moodle/multitenancy/mattan',
      'dataroot' => 'mattan',
      'dbhost' => 'localhost',
      'dbname' => 'moodlemattan',
      'dbuser' => 'root',
      'dbpass' => 'root',
      'prefix' => 'mdl_',
      'dbtype' => 'mysqli',
      'dblibrary' => 'native',
      'dboptions' => 
      array (
      ),
    ),
  ),
  'by_host' => 
  array (
  ),
);
