<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_multitenancy;

defined('MOODLE_INTERNAL') || die();

/**
 * Creates one directory per tenant under local/multitenancy/users/{shortcode}/
 * so URLs like /local/multitenancy/users/mattan/ work without web server rewrites.
 *
 * @package    local_multitenancy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class gateway_manager {

    /** @var string Tenant shortcode cookie. */
    public const COOKIE_NAME = 'local_mt_sc';

    /** @var string Sticky public wwwroot (must match bootstrap LOCAL_MULTITENANCY_WWWROOT_COOKIE). */
    public const WWWROOT_COOKIE_NAME = 'local_mt_wr';

    /**
     * Path to the users gateway root (dirroot-relative filesystem path).
     *
     * @return string
     */
    public static function gateway_root(): string {
        global $CFG;
        return $CFG->dirroot . '/local/multitenancy/users';
    }

    /**
     * Whether shortcode is safe as a directory name.
     *
     * @param string $code
     * @return bool
     */
    public static function is_safe_shortcode(string $code): bool {
        return (bool) preg_match('/^[a-zA-Z0-9_-]+$/', $code);
    }

    /**
     * PHP source for each tenant gateway index.php (identical file in every tenant folder).
     *
     * @return string
     */
    public static function index_file_contents(): string {
        // Stub version marker: changing this forces gateway_manager::sync() to rewrite tenant index.php files.
        return <<<'PHP'
<?php
// This file is auto-generated by local_multitenancy. Do not edit. Stub v5.

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

register_shutdown_function(static function (): void {
    $err = error_get_last();
    if ($err === null) {
        return;
    }
    $fatals = [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR];
    if (!in_array($err['type'], $fatals, true)) {
        return;
    }
    $msg = $err['message'] . ' in ' . $err['file'] . ':' . $err['line'];
    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/plain; charset=UTF-8');
    }
    echo "\n[PHP fatal] ", $msg, "\n";
});

$d = __DIR__;
$cfgroot = null;
while ($d !== '/' && $d !== '' && $d !== '.') {
    $cfgfile = $d . DIRECTORY_SEPARATOR . 'config.php';
    if (is_readable($cfgfile)) {
        $cfgroot = $d;
        break;
    }
    $parent = dirname($d);
    if ($parent === $d) {
        break;
    }
    $d = $parent;
}
if ($cfgroot === null) {
    http_response_code(500);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Moodle config.php not found. Started from: ' . __DIR__;
    exit(1);
}

if (!defined('LOCAL_MULTITENANCY_ENTRY_SHORTCODE')) {
    define('LOCAL_MULTITENANCY_ENTRY_SHORTCODE', basename(__DIR__));
}

try {
    require $cfgroot . DIRECTORY_SEPARATOR . 'config.php';
} catch (Throwable $e) {
    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/plain; charset=UTF-8');
    }
    echo get_class($e), ': ', $e->getMessage(), "\n", $e->getFile(), ':', $e->getLine(), "\n\n", $e->getTraceAsString();
    exit(1);
}

// Gateway is an entry point only: select tenant + set cookies, then continue into Moodle.
if (!headers_sent()) {
    $target = (isset($CFG) && !empty($CFG->wwwroot)) ? rtrim((string) $CFG->wwwroot, '/') . '/' : '/';
    header('Location: ' . $target, true, 303);
    exit;
}

PHP;
    }

    /**
     * Sync gateway directories with the tenant table (enabled tenants only).
     *
     * @return void
     */
    public static function sync(): void {
        global $DB;

        $root = self::gateway_root();
        if (!is_dir($root) && !make_writable_directory($root, false)) {
            return;
        }

        $wanted = [];
        $records = $DB->get_records('local_multitenancy_tenant', ['enabled' => 1], 'id ASC');
        foreach ($records as $r) {
            if (!self::is_safe_shortcode($r->shortcode)) {
                continue;
            }
            $wanted[$r->shortcode] = true;
            $dir = $root . '/' . $r->shortcode;
            if (!is_dir($dir) && !mkdir($dir, 02770, true)) {
                continue;
            }
            $index = $dir . '/index.php';
            $contents = self::index_file_contents();
            if (!is_readable($index) || file_get_contents($index) !== $contents) {
                file_put_contents($index, $contents);
                @chmod($index, 0660);
            }
        }

        if (!($dh = opendir($root))) {
            return;
        }
        while (($name = readdir($dh)) !== false) {
            if ($name === '.' || $name === '..') {
                continue;
            }
            $path = $root . '/' . $name;
            if (!is_dir($path)) {
                continue;
            }
            if (!self::is_safe_shortcode($name)) {
                continue;
            }
            if (isset($wanted[$name])) {
                continue;
            }
            self::remove_directory($path);
        }
        closedir($dh);
    }

    /**
     * @param string $dir Absolute path
     * @return void
     */
    protected static function remove_directory(string $dir): void {
        if (!is_dir($dir)) {
            return;
        }
        $items = scandir($dir);
        if ($items === false) {
            return;
        }
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $path = $dir . '/' . $item;
            if (is_dir($path)) {
                self::remove_directory($path);
            } else {
                @unlink($path);
            }
        }
        @rmdir($dir);
    }
}
