<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_multitenancy;

defined('MOODLE_INTERNAL') || die();

/**
 * Writes registry.php consumed by bootstrap.php before Moodle starts.
 *
 * @package    local_multitenancy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class registry_writer {

    /**
     * Rebuild registry.php from the database.
     *
     * @return bool True if a file was written
     */
    public static function sync(): bool {
        global $CFG, $DB;

        $dir = get_config('local_multitenancy', 'registrydir');
        if (!$dir) {
            return false;
        }
        $dir = rtrim($dir, "/\\\0");
        if ($dir === '') {
            return false;
        }

        if (!is_dir($dir) && !make_writable_directory($dir, false)) {
            return false;
        }

        $pathprefix = get_config('local_multitenancy', 'pathprefix');
        if (empty($pathprefix)) {
            $pathprefix = '/multitenancy';
        }
        $pathprefix = '/' . trim((string) $pathprefix, "/\\\0");
        if ($pathprefix === '/') {
            $pathprefix = '/multitenancy';
        }

        $parentroot = rtrim($CFG->wwwroot, '/');

        $routingmode = get_config('local_multitenancy', 'routingmode');
        if ($routingmode === false || $routingmode === '') {
            $routingmode = 'stub';
        }

        $records = $DB->get_records('local_multitenancy_tenant', null, 'sortorder ASC, id ASC');
        $byshort = [];
        $byhost = [];
        $stubcodes = [];

        foreach ($records as $r) {
            $dboptions = [];
            if (!empty($r->dboptions)) {
                $decoded = json_decode($r->dboptions, true);
                if (is_array($decoded)) {
                    $dboptions = $decoded;
                }
            }

            $storedwww = trim((string) $r->wwwroot);
            if ($routingmode === 'stub') {
                // Same URL space as parent: tenant via /multitenancy/CODE/ stubs + cookie (no Apache rewrite).
                $effwww = $parentroot;
            } else if ($storedwww !== '') {
                $effwww = rtrim($storedwww, '/');
            } else {
                $effwww = $parentroot . $pathprefix . '/' . $r->shortcode;
            }

            $row = [
                'shortcode' => $r->shortcode,
                'name' => $r->name,
                'enabled' => (int) $r->enabled,
                'wwwroot' => $effwww,
                'dataroot' => $r->dataroot,
                'dbhost' => $r->dbhost,
                'dbname' => $r->dbname,
                'dbuser' => $r->dbuser,
                'dbpass' => (string) $r->dbpass,
                'prefix' => $r->dbprefix,
                'dbtype' => $r->dbtype,
                'dblibrary' => $r->dblibrary,
                'dboptions' => $dboptions,
            ];

            $byshort[$r->shortcode] = $row;
            if (!empty($r->enabled)) {
                $stubcodes[] = $r->shortcode;
            }

            $host = trim((string) $r->host);
            if ($host !== '') {
                if (function_exists('mb_strtolower')) {
                    $host = mb_strtolower($host, 'UTF-8');
                } else {
                    $host = strtolower($host);
                }
                $byhost[$host] = $row;
            }
        }

        $map = [
            'routing' => $routingmode,
            'path_prefix' => $pathprefix,
            'by_shortcode' => $byshort,
            'by_host' => $byhost,
        ];

        $header = "<?php\n// This file is auto-generated by local_multitenancy. Do not edit manually.\n\n";
        $body = 'return ' . var_export($map, true) . ";\n";
        $target = $dir . '/registry.php';

        if (file_put_contents($target, $header . $body) === false) {
            return false;
        }
        @chmod($target, 0660);

        stub_manager::sync_all($stubcodes);

        return true;
    }
}
