<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_multitenancy;

defined('MOODLE_INTERNAL') || die();

/**
 * Writes registry.php consumed by bootstrap.php before Moodle starts.
 *
 * @package    local_multitenancy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class registry_writer {

    /**
     * Rebuild registry.php from the database.
     *
     * @return bool True if a file was written
     */
    public static function sync(): bool {
        global $DB;

        $dir = get_config('local_multitenancy', 'registrydir');
        if (!$dir) {
            return false;
        }
        $dir = rtrim($dir, "/\\\0");
        if ($dir === '') {
            return false;
        }

        if (!is_dir($dir) && !make_writable_directory($dir, false)) {
            return false;
        }

        $records = $DB->get_records('local_multitenancy_tenant', null, 'sortorder ASC, id ASC');
        $map = [];
        foreach ($records as $r) {
            $host = $r->host;
            if (function_exists('mb_strtolower')) {
                $host = mb_strtolower($host, 'UTF-8');
            } else {
                $host = strtolower($host);
            }
            $dboptions = [];
            if (!empty($r->dboptions)) {
                $decoded = json_decode($r->dboptions, true);
                if (is_array($decoded)) {
                    $dboptions = $decoded;
                }
            }
            $wwwroot = \local_multitenancy_normalize_public_wwwroot((string) $r->wwwroot);
            $map[$host] = [
                'shortcode' => $r->shortcode,
                'name' => $r->name,
                'enabled' => (int) $r->enabled,
                'midurim' => (string) ($r->midurim ?? ''),
                'midurimformat' => (int) ($r->midurimformat ?? FORMAT_HTML),
                'wwwroot' => $wwwroot,
                'dataroot' => $r->dataroot,
                'dbhost' => $r->dbhost,
                'dbname' => $r->dbname,
                'dbuser' => $r->dbuser,
                'dbpass' => (string) $r->dbpass,
                'prefix' => $r->dbprefix,
                'dbtype' => $r->dbtype,
                'dblibrary' => $r->dblibrary,
                'dboptions' => $dboptions,
            ];
        }

        $header = "<?php\n// This file is auto-generated by local_multitenancy. Do not edit manually.\n\n";
        $body = 'return ' . var_export($map, true) . ";\n";
        $target = $dir . '/registry.php';

        if (file_put_contents($target, $header . $body) === false) {
            return false;
        }
        @chmod($target, 0660);

        return true;
    }
}
