<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_multitenancy;

defined('MOODLE_INTERNAL') || die();

/**
 * Creates physical entry scripts under $CFG->dirroot/multitenancy/{shortcode}/index.php
 * so Apache serves /multitenancy/CODE/ without rewrite rules.
 *
 * @package    local_multitenancy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class stub_manager {

    /** @var string Cookie name for tenant shortcode (path=/). */
    public const COOKIE_NAME = 'local_multitenancy_sc';

    /**
     * @param string $shortcode
     * @return bool
     */
    public static function is_safe_shortcode(string $shortcode): bool {
        return (bool) preg_match('/^[A-Za-z0-9_]+$/', $shortcode);
    }

    /**
     * @return string Absolute path to .../moodle/multitenancy
     */
    public static function stub_base_dir(): string {
        global $CFG;
        return $CFG->dirroot . DIRECTORY_SEPARATOR . 'multitenancy';
    }

    /**
     * Sync stub directories with current tenants (routing mode stub only).
     *
     * @param string[] $shortcodes Enabled tenant codes from DB
     * @return void
     */
    public static function sync_all(array $shortcodes): void {
        global $CFG;

        $routing = get_config('local_multitenancy', 'routingmode');
        if ($routing === 'rewrite') {
            self::remove_all_stub_dirs();
            return;
        }

        $base = self::stub_base_dir();
        if (!is_dir($base)) {
            if (!make_writable_directory($base, false)) {
                return;
            }
        }

        $wanted = [];
        foreach ($shortcodes as $code) {
            if (!self::is_safe_shortcode($code)) {
                continue;
            }
            $wanted[$code] = true;
            self::write_stub($code);
        }

        if (!is_dir($base)) {
            return;
        }
        $items = scandir($base, SCANDIR_SORT_NONE);
        if ($items === false) {
            return;
        }
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $path = $base . DIRECTORY_SEPARATOR . $item;
            if (!is_dir($path)) {
                continue;
            }
            if (!isset($wanted[$item])) {
                self::remove_dir($path);
            }
        }
    }

    /**
     * @return void
     */
    public static function remove_all_stub_dirs(): void {
        $base = self::stub_base_dir();
        if (!is_dir($base)) {
            return;
        }
        $items = scandir($base, SCANDIR_SORT_NONE);
        if ($items === false) {
            return;
        }
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $path = $base . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) {
                self::remove_dir($path);
            }
        }
    }

    /**
     * @param string $shortcode
     * @return void
     */
    protected static function write_stub(string $shortcode): void {
        global $CFG;

        $dir = self::stub_base_dir() . DIRECTORY_SEPARATOR . $shortcode;
        if (!make_writable_directory($dir, false) && !is_dir($dir)) {
            return;
        }

        $codeexport = var_export($shortcode, true);
        $cookiename = var_export(self::COOKIE_NAME, true);
        $content = "<?php\n";
        $content .= "// Auto-generated by local_multitenancy — do not edit.\n";
        $content .= "\$_SERVER['MOODLE_TENANT'] = {$codeexport};\n";
        $content .= "\$__cn = {$cookiename};\n";
        $content .= "\$__cv = rawurlencode({$codeexport});\n";
        $content .= "setcookie(\$__cn, \$__cv, [\n";
        $content .= "    'expires' => time() + 2592000,\n";
        $content .= "    'path' => '/',\n";
        $content .= "    'secure' => (!empty(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] !== 'off' && \$_SERVER['HTTPS'] !== 'OFF'),\n";
        $content .= "    'httponly' => true,\n";
        $content .= "    'samesite' => 'Lax',\n";
        $content .= "]);\n";
        $content .= "\$_COOKIE[\$__cn] = \$__cv;\n";
        $content .= "\$dr = dirname(__DIR__, 2);\n";
        $content .= "chdir(\$dr);\n";
        $content .= "require \$dr . DIRECTORY_SEPARATOR . 'config.php';\n";
        $content .= "require \$dr . DIRECTORY_SEPARATOR . 'index.php';\n";

        $target = $dir . DIRECTORY_SEPARATOR . 'index.php';
        file_put_contents($target, $content);
        @chmod($target, ($CFG->filepermissions ?? 0666) | 0444);
    }

    /**
     * @param string $dir
     * @return void
     */
    protected static function remove_dir(string $dir): void {
        if (!is_dir($dir)) {
            return;
        }
        $files = array_diff(scandir($dir, SCANDIR_SORT_NONE) ?: [], ['.', '..']);
        foreach ($files as $f) {
            $p = $dir . DIRECTORY_SEPARATOR . $f;
            if (is_dir($p)) {
                self::remove_dir($p);
            } else {
                @unlink($p);
            }
        }
        @rmdir($dir);
    }
}
