<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Hebrew language pack.
 *
 * @package    local_multitenancy
 * @copyright  2026
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'ריבוי דיירים (DB ו־moodledata נפרדים)';
$string['manage_tenants'] = 'ניהול דיירים (טננטים)';
$string['addtenant'] = 'הוספת דייר';
$string['edittenant'] = 'עריכת דייר';
$string['deletetenant'] = 'מחיקת דייר';
$string['shortcode'] = 'קוד דייר';
$string['shortcode_help'] = 'מזהה קצר וייחודי לשימוש ב־CLI (משתנה סביבה MOODLE_TENANT). מומלץ אותיות, מספרים וקו תחתון בלבד.';
$string['errorshortcodenotallowed'] = 'קוד הדייר חייב להיבחר מתוך רשימת קודי הדיירים המותרים.';
$string['manageallowedshortcodes'] = 'ניהול קודי דיירים מותרים';
$string['allowedshortcodes'] = 'קודי דיירים מותרים';
$string['allowedshortcodes_help'] = 'הזן קוד דייר אחד בכל שורה. קודים אלו יוצגו כ־dropdown במסך הוספת דייר.';
$string['allowedshortcodesdesc'] = 'הגדר כאן את רשימת קודי הדייר האפשריים. במסך "הוספת דייר", שדה קוד הדייר יוצג כרשימה נפתחת לפי רשימה זו.';
$string['allowedshortcodessaved'] = 'רשימת קודי הדיירים המותרים נשמרה.';
$string['errorallowedshortcodesinvalid'] = 'קוד דייר לא תקין "{$a}". מותר להשתמש רק באותיות, מספרים וקו תחתון.';
$string['host'] = 'מארח HTTP (Host)';
$string['host_help'] = 'לדייר לפי תת־דומיין: ערך Host מדויק (למשל school1.example.com). לדיירים לפי נתיב על אותו דומיין כמו האב, השתמש במארח־מקום ייחודי לכל דייר (למשל mattan.path.local) שלא מגיע בקשות אמיתיות — הזיהוי הוא דרך /local/multitenancy/users/{קוד}/ ועוגייה.';
$string['wwwroot'] = 'כתובת wwwroot של הדייר';
$string['wwwroot_help'] = 'כאן מודל צריך את אותו בסיס ציבורי כמו ב־config.php של האתר האב (למשל https://yoursite.example או https://yoursite.example/moodle). כתובת ה־gateway ‎https://…/local/multitenancy/users/{קוד}/‎ היא אופציונלית — אותו מידע כמו בסיס + קוד דייר, והתוסף מנרמל ממנה את הבסיס. לדייר לפי נתיב: מספיק רק בסיס האתר ואין כפילות מיותרת. לדייר לפי תת־דומיין: כתובת האתר המלאה של הדייר.';
$string['errorwwwrootgatewaymismatch'] = 'ב־wwwroot מופיע ‎/local/multitenancy/users/…‎ אבל הקטע בנתיב ("{$a->found}") לא תואם לקוד הדייר ("{$a->expected}").';
$string['gatewayurl'] = 'כתובת Gateway';
$string['gatewayexplain'] = 'לכל דייר מופעל נוצרת תיקייה local/multitenancy/users/{קוד דייר}/ כך שכתובות כמו .../users/mattan/ עובדות בלי rewrite ב־Apache. הכניסה מגדירה עוגיות (קוד דייר + wwwroot ציבורי) כדי שבדיקות ה־URL של Moodle יתאימו ל־SCRIPT_NAME. /local/multitenancy/leave.php מנקה עוגיות וחוזר לאתר האב. לאחר שינוי קוד דייר יש לשמור דייר או לבנות מחדש את ה־registry.';
$string['dataroot'] = 'נתיב moodledata של הדייר';
$string['dbhost'] = 'שרת מסד נתונים';
$string['dbname'] = 'שם מסד נתונים';
$string['dbuser'] = 'משתמש מסד';
$string['dbpass'] = 'סיסמת מסד';
$string['dbprefix'] = 'קידומת טבלאות';
$string['dbtype'] = 'סוג מסד';
$string['dblibrary'] = 'ספריית מסד';
$string['enabled'] = 'מופעל';
$string['dboptions'] = 'dboptions (JSON)';
$string['dboptions_help'] = 'אובייקט JSON אופציונלי שמוזג ל־$CFG->dboptions עבור הדייר. השאר ריק לשימוש בברירות מחדל מ־config.php.';
$string['dboptionsexample'] = 'דוגמת JSON (אובייקט בלבד): {"dbpersist": false, "dbport": 3306}. השתמש בזוגות מפתח/ערך כמו ב־$CFG->dboptions. לא לעטוף ב־[] ולא להשאיר פסיק מיותר בסוף.';
$string['sortorder'] = 'סדר מיון';
$string['autogeneratedtenantfields'] = 'Host, כתובת wwwroot ונתיב dataroot של הדייר נוצרים אוטומטית לפי קוד הדייר והגדרות האתר הראשי.';
$string['autogenerateddbfields'] = 'שרת/שם/משתמש/סיסמת DB, קידומת טבלאות, סוג מסד וספריית מסד נוצרים אוטומטית לפי קונפיג האתר הראשי וקוד הדייר. סכימת DB של הדייר נוצרת אוטומטית בזמן שמירה.';
$string['initdbfromparent'] = 'אתחול DB דייר מהאתר הראשי אם הוא ריק';
$string['initdbfromparent_help'] = 'כאשר מסומן, שמירת הדייר תעתיק אוטומטית את DB Moodle הראשי אל DB הדייר אם כרגע אין בו טבלאות.';
$string['copycoursesdata'] = 'להעתיק גם קורסים וכל נתוני הקורסים';
$string['copycoursesdata_help'] = 'מסומן: העתקה מלאה כולל כל הקורסים. לא מסומן: תועתק רק סביבת קורס החזית (front page), ונתונים המשויכים לקורסים אחרים ידולגו.';
$string['dbprovisioned'] = 'DB הדייר "{$a}" אותחל מתוך DB האתר הראשי.';
$string['dbprovisionednocourses'] = 'DB הדייר "{$a}" אותחל מתוך DB האתר הראשי ללא העתקת נתוני קורסים (מלבד קורס חזית).';
$string['dbprovisionskippednotempty'] = 'DB הדייר "{$a}" כבר מכיל טבלאות, לכן האתחול דולג.';
$string['dbprovisionskippedunsupported'] = 'אתחול DB אוטומטי נתמך כרגע רק לדרייברים ממשפחת mysql ול־pgsql (dbtype של הדייר: "{$a}").';
$string['dbprovisionfailed'] = 'אתחול DB אוטומטי לדייר נכשל: {$a}';
$string['datarootautocreatefailed'] = 'לא ניתן ליצור אוטומטית את dataroot של הדייר: {$a}. צור ידנית וודא הרשאות כתיבה לשרת.';
$string['dbschemaautocreated'] = 'סכימת מסד הנתונים של הדייר קיימת ומוכנה: {$a}.';
$string['dbschemaautocreatefailed'] = 'לא ניתן היה להבטיח אוטומטית את סכימת מסד הנתונים של הדייר: {$a}';
$string['footertenantcontext'] = 'הקשר דייר פעיל: {$a->name} ({$a->code})';
$string['footerleavetenant'] = 'יציאה מהדייר';
$string['logintenantpicker_title'] = 'כניסה לדייר';
$string['logintenantpicker_desc'] = 'בחר דייר כדי להמשיך להקשר ההתחברות שלו.';
$string['passwordunchanged'] = 'השאר ריק כדי לשמור על הסיסמה הקיימת';
$string['errorshortcodeexists'] = 'קוד הדייר כבר בשימוש.';
$string['errorhostexists'] = 'מארח זה כבר משויך לדייר אחר.';
$string['errordboptionsjson'] = 'JSON לא תקין עבור dboptions.';
$string['errorwwwrootinvalid'] = 'wwwroot חייב להיות כתובת מלאה שמתחילה ב־http:// או https:// (למשל https://yoursite.example/local/multitenancy/users/קוד-הדייר/).';
$string['errordatarootnotabsolute'] = 'dataroot חייב להיות נתיב מוחלט בשרת (למשל /var/moodledata/tenant1), לא שם קצר.';
$string['registrydir'] = 'תיקיית registry (נתיב מוחלט)';
$string['registrydir_desc'] = 'תיקייה בשרת שבה נכתב registry.php. חייבת להתאים ל־MULTITENANCY_REGISTRY_DIR ב־config.php. למשתמש שרת האינטרנט חייבת להיות הרשאת כתיבה.';
$string['registrydirmissing'] = 'תיקיית ה־registry לא הוגדרה. הגדר אותה בניהול האתר ← תוספים ← תוספים מקומיים ← ריבוי דיירים, ואז שמור דייר מחדש או לחץ על בנייה מחדש של registry.';
$string['registrydirset'] = 'תיקיית registry: {$a}';
$string['registryupdated'] = 'קובץ ה־registry עודכן בהצלחה.';
$string['registrynotwritten'] = 'קובץ ה־registry לא נכתב. בדוק את הנתיב והרשאות הכתיבה.';
$string['notenants'] = 'עדיין לא הוגדרו דיירים.';
$string['deleteconfirm'] = 'למחוק את הדייר "{$a}"? פעולה זו לא מוחקת את מסד הנתונים או קבצי ה־moodledata של הדייר.';
$string['tenantdeleted'] = 'הדייר נמחק.';
$string['rebuildregistry'] = 'בנייה מחדש של קובץ registry';
$string['configsnippet_title'] = 'קטע ל־config.php';
$string['configsnippet_desc'] = 'הוסף ב־config.php לפני require_once(__DIR__ . \'/lib/setup.php\'). אל תשתמש ב־$CFG->dirroot בשורות האלה: מודל מגדיר אותו רק בתוך setup.php. השתמש ב־__DIR__ לנתיב ל־bootstrap. לדוגמה: if (!defined(\'MULTITENANCY_REGISTRY_DIR\')) { define(\'MULTITENANCY_REGISTRY_DIR\', $CFG->dataroot . \'/multitenancy\'); } require_once(__DIR__ . \'/local/multitenancy/bootstrap.php\'); local_multitenancy_bootstrap($CFG); ודא ש־MULTITENANCY_REGISTRY_DIR תואם להגדרת "תיקיית registry" בתוסף. ב־CLI: export MOODLE_TENANT=קוד_הדייר';
$string['cli_diag_help'] = 'אבחון gateway לריבוי דיירים (דף לבן).

הרץ משורש Moodle, למשל:
  cd /path/to/moodle
  php local/multitenancy/cli/diagnose_gateway.php --shortcode=CODE
  php local/multitenancy/cli/diagnose_gateway.php -s CODE

בודק: MULTITENANCY_REGISTRY_DIR, registry.php, רשומת דייר, wwwroot, dataroot, קובץ gateway, חיבור DB (mysql-family + pgsql), כתובת בדפדפן.

';
$string['cli_diag_invalidshortcode'] = 'קוד דייר לא תקין: {$a}';
$string['cli_diag_registrydirundefined'] = 'MULTITENANCY_REGISTRY_DIR לא מוגדר ב־config.php.';
$string['cli_diag_registrydirmissing'] = 'תיקיית ה־registry לא קיימת: {$a}. צור אותה (mkdir), תן הרשאות לשרת האינטרנט, ואז במודל שמור דייר או בנה מחדש registry.';
$string['cli_diag_registryfilenotfound'] = 'אין עדיין registry.php: {$a}. במודל: ניהול האתר → תוספים מקומיים → Multitenancy — הגדר "תיקיית registry" לתיקייה זו, הוסף דיירים, ואז שמור או בנייה מחדש.';
$string['cli_diag_registryfilenotreadable'] = 'registry.php קיים אבל לא ניתן לקריאה: {$a}. תקן הרשאות (chmod/chown) ל־CLI ולמשתמש שרת האינטרנט.';
$string['cli_diag_registryfileok'] = 'קובץ registry תקין: {$a}';
$string['cli_diag_registryempty'] = 'registry.php ריק או לא מערך.';
$string['cli_diag_tenantnotinregistry'] = 'אין דייר עם הקוד "{$a}" ב־registry — הוסף בניהול והרץ שמירה או בנייה מחדש.';
$string['cli_diag_tenantdisabled'] = 'הדייר "{$a}" מושבת ב־registry.';
$string['cli_diag_tenantenabled'] = 'הדייר "{$a}" מופעל.';
$string['cli_diag_wwwrootinvalid'] = 'wwwroot ב־registry לא URL מלא (ערך: "{$a}").';
$string['cli_diag_wwwrootok'] = 'wwwroot תקין (בסיס ציבורי במודל מפורק מהערך השמור): {$a}';
$string['cli_diag_datarootnotabsolute'] = 'dataroot לא נתיב מוחלט (ערך: "{$a}").';
$string['cli_diag_datarootabsolute'] = 'dataroot מוחלט: {$a}';
$string['cli_diag_datarootmissing'] = 'תיקיית dataroot לא קיימת: {$a}';
$string['cli_diag_datarootnotwritable'] = 'אין כתיבה ל־dataroot למשתמש זה: {$a}';
$string['cli_diag_datarootok'] = 'dataroot קיים וניתן לכתיבה: {$a}';
$string['cli_diag_gatewayindexmissing'] = 'חסר gateway index.php: {$a} — שמור דייר או בנה מחדש registry.';
$string['cli_diag_gatewayindexok'] = 'gateway index.php תקין: {$a}';
$string['cli_diag_gatewaystuboutdated'] = 'תוכן index.php שונה מה־stub של התוסף — שמור דייר או בנה מחדש registry.';
$string['cli_diag_dbconnectok'] = 'חיבור למסד הצליח (מסד: {$a}).';
$string['cli_diag_dbskipped'] = 'דילוג על בדיקת DB (מנהל: {$a}); הסקריפט בודק רק mysqli/mariadb/auroramysql/pgsql.';
$string['cli_diag_dbconnectfail'] = 'חיבור למסד נכשל: {$a}';
$string['cli_diag_hintweb'] = 'כתובת gateway צפויה בדפדפן: {$a}';
$string['cli_diag_summary_ok'] = 'כל הבדיקות הקריטיות עברו. אם עדיין דף לבן: בדוק SCRIPT_NAME, HTTPS/עוגיות, לוגי PHP/שרת, וב־Network בדפדפן.';
$string['cli_diag_summary_fail'] = 'שורות [ERR] למעלה מסבירות את הבעיה. תקן, הרץ שוב את הסקריפט.';
