<?php
        // This file is auto-generated by local_multitenancy. Do not edit. Stub v6.

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

register_shutdown_function(static function (): void {
    $err = error_get_last();
    if ($err === null) {
        return;
    }
    $fatals = [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR];
    if (!in_array($err['type'], $fatals, true)) {
        return;
    }
    $msg = $err['message'] . ' in ' . $err['file'] . ':' . $err['line'];
    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/plain; charset=UTF-8');
    }
    echo "\n[PHP fatal] ", $msg, "\n";
});

$d = __DIR__;
$cfgroot = null;
while ($d !== '/' && $d !== '' && $d !== '.') {
    $cfgfile = $d . DIRECTORY_SEPARATOR . 'config.php';
    if (is_readable($cfgfile)) {
        $cfgroot = $d;
        break;
    }
    $parent = dirname($d);
    if ($parent === $d) {
        break;
    }
    $d = $parent;
}
if ($cfgroot === null) {
    http_response_code(500);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Moodle config.php not found. Started from: ' . __DIR__;
    exit(1);
}

if (!defined('LOCAL_MULTITENANCY_ENTRY_SHORTCODE')) {
    define('LOCAL_MULTITENANCY_ENTRY_SHORTCODE', basename(__DIR__));
}

try {
    require $cfgroot . DIRECTORY_SEPARATOR . 'config.php';
} catch (Throwable $e) {
    if (!headers_sent()) {
        http_response_code(500);
        header('Content-Type: text/plain; charset=UTF-8');
    }
    echo get_class($e), ': ', $e->getMessage(), "\n", $e->getFile(), ':', $e->getLine(), "\n\n", $e->getTraceAsString();
    exit(1);
}

// Gateway is an entry point only: select tenant + set cookies, then continue into Moodle.
if (!headers_sent()) {
    $target = (isset($CFG) && !empty($CFG->wwwroot)) ? rtrim((string) $CFG->wwwroot, '/') . '/' : '/';
    header('Location: ' . $target, true, 303);
    exit;
}
