<?php
// This file is auto-generated by local_multitenancy. Do not edit.

$d = __DIR__;
while ($d !== '/' && $d !== '' && !is_readable($d . DIRECTORY_SEPARATOR . 'config.php')) {
    $d = dirname($d);
}
if ($d === '/' || $d === '') {
    http_response_code(500);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Moodle config.php not found.';
    exit(1);
}

define('LOCAL_MULTITENANCY_ENTRY_SHORTCODE', basename(__DIR__));
require $d . DIRECTORY_SEPARATOR . 'config.php';
